name: 启动器问题报告 ( Installer Bug Report )
description: BAAS启动器无法更新 / 依赖无法安装
title: "[Installer Bug]: "
labels: ["问题修复", "GUI相关", "启动器问题"]
assignees:
  - Kiramei,pur1fying
body:
  - type: dropdown
    id: version
    attributes:
      label: 启动器版本 ( Installer Version )
      description: BAAS启动器的版本
      options:
        - 1.4.3 (Latest)
        - 1.4.2
        - 1.4.1
        - 1.4.0
        - 1.3.0.1 Beta
        - 1.3.0
        - 1.2.0
        - 1.1.3
        - 1.1.2
        - 1.1.1
        - 1.1.0
        - 1.0 Beta
      default: 0
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## 请根据提示提交相关材料

  - type: dropdown
    id: operating_system
    attributes:
      label: 操作系统 ( OS )
      description: 请选择您使用的操作系统
      options:
        - Windows
        - macOS
        - Linux
      default: 0
    validations:
      required: true

  - type: textarea
    id: bug_description
    attributes:
      label: 错误描述 ( Bug Description )
      description: 你提供的信息越详细, 越能帮助我们快速定位问题
      placeholder: |
        请详细描述：
        1. 遇到的具体问题现象
        2. 出现问题前的操作步骤
        3. 问题是否稳定复现
    validations:
      required: true

  - type: textarea
    id: error_logs
    attributes:
      label: 报错日志 / 截图 / 录屏 ( Related Log )
      description: |
        请提供以下材料之一或多个：
        - 启动器运行时的报错日志
        - 录屏
      placeholder: |
        请在此处粘贴错误日志 / 截图 / 录屏
    validations:
      required: true

  - type: textarea
    id: script_config
    attributes:
      label: 启动器配置文件 ( Installer Config )
      description: |
        如果你的BAAS版本高于1.4.0, 请上传setup.toml
      placeholder: |
        上传setup.toml
    validations:
      required: false

  - type: textarea
    id: additional_info
    attributes:
      label: 补充信息 ( Additional Info )
      description: 可能有助于解决问题的信息
      placeholder: |
        例如：
        - 尝试过的解决方法
        - 其他相关设置
    validations:
      required: false